# Generated by Django 5.2.7 on 2025-11-13 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='edad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='nuevo_ingreso',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='telefono',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='curso',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
    ]
